# Generated by Django 5.2 on 2025-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='elevating_twist',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
