# Generated by Django 5.2 on 2025-10-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_generator', '0002_recipe_elevating_twist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ai_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
